#!/sbin/sh

# triget button-backlight
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/button-backlight/brightness

# trigger red, orange, yellow, green, blue, purple LED :)
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/red/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/green/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/blue/brightness
usleep 200000
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/red/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/green/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/blue/brightness
usleep 200000
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/red/brightness
echo '50' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/green/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/blue/brightness
usleep 200000
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/red/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/green/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/blue/brightness
usleep 200000
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/red/brightness
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/green/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/blue/brightness
usleep 200000
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/red/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/green/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/blue/brightness
usleep 200000
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/red/brightness
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/green/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/blue/brightness
usleep 200000
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/red/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/green/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/blue/brightness
usleep 200000
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/red/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/green/brightness
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/blue/brightness
usleep 200000
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/red/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/green/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/blue/brightness
usleep 200000
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/red/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/green/brightness
echo '255' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/blue/brightness
usleep 200000

# trigger vibration
echo '200' > /sys/class/timed_output/vibrator/enable

# disable button-backlight
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/button-backlight/brightness

# disable LEDs
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/red/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/green/brightness
echo '0' > /sys/devices/platform/nmk-i2c.2/i2c-2/2-0040/leds/blue/brightness

cat /dev/input/event1 > /dev/keycheck &
sleep 3

kill -9 $!
