#!/system/bin/sh
# uncomment any of them if needed

###########################
# CPU governor            #
# Default: ondemand       #
###########################
echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

###########################
# CPU frequency           #
# Default: 200 ~ 1150     #
# Min freq.: 200          #
# Max freq.: 1000         #
###########################
echo 200000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 1000000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

###########################
# Scheduler               #
# Default: sio            #
###########################
echo "sio" > /sys/block/mmcblk0/queue/scheduler
