local-phone-apps = \
                    AppEnabler \
                    ATService \
                    ApplicationsProvider \
                    AudioEffectService \
                    Bluetooth \
                    bootinfo \
                    CameraExtensionPermission \
                    CdfInfoAccessor \
                    CertInstaller \
                    CredentialManagerService \
                    DefaultCapabilities \
                    DefaultContainerService \
                    device-monitor \
                    enhancedusbux \
                    GenericApplicationInstaller \
                    Initial-boot-setup \
                    JapaneseIME \
                    MediaProvider \
                    MemcardTransportService \
                    MusicFX \
                    Nfc \
                    nfc-handover \
                    NoiseField \
                    PackageInstaller \
                    Radio3 \
                    SemcCamera3D \
                    SemcCameraUI \
                    SemcIllumination \
                    SemcSimDetection \
                    ServiceMenu \
                    SoundEnhancement \
                    textinput-chn \
                    textinput-tng \
                    usb-mtp-backup-transport \
                    usb-mtp-marlin-wrapper \
                    usb-mtp-update-wrapper \
                    usb-mtp-vendor-extension-service \
                    usbotg \
                    UsbTransportService \
                    UserDictionaryProvider \
                    WapiCustomization \
                    WapPush

local-remove-apps = \
                    Backup-Restore \
                    Backup-wizard \
                    Browser \
                    CalendarProvider \
                    ContactsImport \
                    Conversations \
                    CosmicFlow \
                    CustomizationPresetContacts \
                    CustomizationProvider \
                    CustomizedApplicationInstaller \
                    CustomizedSettings \
                    DownloadProvider \
                    DownloadProviderUi \
                    DrmDialogs \
                    DrmProvider \
                    Exchange \
                    Gmail \
                    GMS_Maps \
                    GoogleBackupTransport \
                    GoogleCalendarSyncAdapter \
                    GoogleContactsSyncAdapter \
                    GoogleFeedback \
                    GoogleLoginService \
                    GoogleLyricsPlugin \
                    GooglePartnerSetup \
                    GoogleQuickSearchBox \
                    GoogleServicesFramework \
                    helpapp \
                    HTMLViewer \
                    IddAgent \
                    InfiniteView \
                    KeyChain \
                    livewaremanager \
                    LocalContacts \
                    MediaUploader \
                    MusicWidget \
                    NetworkLocation \
                    NewSoftwareChecker \
                    OMAClientProvisioning \
                    OmaDownload \
                    OmaV1AgentDownloadServices \
                    OneTimeInitializer \
                    OnOffTools \
                    PartnerBookmarksProvider \
                    Phonesky \
                    PhotoWidget \
                    PicoTts \
                    PMSservice \
                    PMSserviceTrigger \
                    POBoxSknMono \
                    POBoxSknPink \
                    POBoxSknSelector \
                    POBoxSknWood \
                    PostViewer \
                    ReadyToRun \
                    RecentCallsWidget \
                    RemoteControlService \
                    retaildemo \
                    SecureClockJava \
                    SemcAlbum \
                    SemcAutoPowerOff \
                    SemcCalculator \
                    SemcCalendar \
                    SemcClock \
                    SemcCnapProvider \
                    SemcContactsProvider \
                    SemcCrashMonitor \
                    SemcDlna \
                    SemcDlnaHandover \
                    SemcEmail \
                    SEMCFacebookProxy \
                    SemcMetadataCleanup \
                    SemcMusic \
                    SemcMusicVisualizer \
                    SemcNotes \
                    SemcPhone \
                    SemcPhotoEditor \
                    SemcPowerSaveModule \
                    semcservice \
                    SemcSettings \
                    SEMCSetupWizard \
                    SemcSnpPlatformUtil \
                    SemcSnpVideoPlayer \
                    SemcTelephonyProvider \
                    SemcVideo \
                    SemcWarrantyTime \
                    Settings \
                    SettingsProvider \
                    ShutDownAnimation \
                    SmartSearch \
                    SoundLevelAlert \
                    SoundPicker \
                    Stk \
                    storefront \
                    SuperStamina \
                    SwiqiMasterReset \
                    TetherEntitlementCheck \
                    torch \
                    UnsupportedHeadsetNotifier \
                    UpdateCenter \
                    UseragentProvider \
                    UxpNxtLockScreen \
                    VerifyCertificatesDummyAppApplication \
                    VerifyCertificatesDummyAppMedia \
                    VerifyCertificatesDummyAppPlatform \
                    VerifyCertificatesDummyAppShared \
                    VoiceDialer \
                    VoiceSearch \
                    VoipCallLogProvider \
                    VpnDialogs \
                    WallpaperPicker \
                    WiFiApState
